### PR TITLE
Inserimento Prodotto Agricoltore

### PR DESCRIPTION
**Pull request by MauroP001**
Creazione del form di inserimento per un prodotto di un agricoltore.

### CODE REVIEW

**Comment by deg997** [comment]
<h1>Ciao</h1>

**Comment by deg997** [comment]
<h1>Prima parte della revisione</h1>
@MauroP001 questa è la prima parte della revisione della tua pull-request. La seconda parte la farà @davidexvii-uni su altri file della pull-request. Ci sono pochi problemi da fixare e di facile risoluzione prima di poter chiudere la pull-request.
<h2>Sono inclusi i seguenti file:</h2>
<ul>
  <li>com/greenbridge/services/ProdottoService.java</li>
  <li>com/greenbridge/repositories/ProdottoRepository.java</li>
  <li>com/greenbridge/entities/Prodotto.java</li>
</ul>
<h2>ProdottoService.java</h2>
<table>
<tbody>
<tr>
<th>Severity</th>
<th>Category</th>
<th>Rule</th>
<th>Message</th>
<th>Line</th></tr>
<tr>
<td> Error</td>
<td>imports</td>
<td>RedundantImport</td>
<td>Duplicate import to line 4 - com.greenbridge.repositories.ProdottoRepository.</td>
<td>8</td></tr>
<tr>
<td>Error</td>
<td>imports</td>
<td>UnusedImports</td>
<td>Unused import - java.util.Base64.</td>
<td>10</td></tr>
<tr>
<td>Error</td>
<td>whitespace</td>
<td>WhitespaceAround</td>
<td>'{' is not preceded with whitespace.</td>
<td>18</td></tr>
<tr>
<td>Error</td>
<td>whitespace</td>
<td>WhitespaceAround</td>
<td>'{' is not preceded with whitespace.</td>
<td>22</td></tr>
<tr>
<td>Error</td>
<td>sizes</td>
<td>LineLength</td>
<td>Line is longer than 80 characters (found 91).</td>
<td>23</td></tr>
<tr>
<td>Error</td>
<td>whitespace</td>
<td>WhitespaceAround</td>
<td>'{' is not preceded with whitespace.</td>
<td>25</td></tr>
</tbody>
</table>
<h2>ProdottoRepository.java</h2>
<table>
<tbody>
<tr>
<th>Severity</th>
<th>Category</th>
<th>Rule</th>
<th>Message</th>
<th>Line</th></tr>
<tr>
<td>Error</td>
<td>whitespace</td>
<td>GenericWhitespace</td>
<td>'&gt;' is followed by an illegal character.</td>
<td>8</td></tr>
 <tr>
<td>Error</td>
<td>whitespace</td>
<td>WhitespaceAround</td>
<td>'{' is not preceded with whitespace.</td>
<td>8</td></tr>
</tbody>
</table>
<h2>Prodotto.java (dalla riga 38 alla 51)</h2>
<table>
<tbody>
<tr>
<th>Severity</th>
<th>Category</th>
<th>Rule</th>
<th>Message</th>
<th>Line</th></tr>
<tr>
<td>Error</td>
<td>sizes</td>
<td>LineLength</td>
<td>Line is longer than 80 characters (found 82).</td>
<td>41</td></tr>
<tr>
<td>Error</td>
<td>sizes</td>
<td>LineLength</td>
<td>Line is longer than 80 characters (found 85).</td>
<td>51</td></tr>
</tbody>
</table>

**Comment by davidexvii-uni** [comment]
<h1>Seconda parte della revisione</h1>
@MauroP001 questa è la seconda parte della revisione della tua pull-request.
<h2>Sono inclusi i seguenti file:</h2>
<ul>
  <li>com/greenbridge/services/ProdottoController.java</li>
  <li>com/greenbridge/entities/Prodotto.java</li>
</ul>
<h2>ProdottoController.java</h2>
<table>
<tbody>
<tr>
<th>Severity</th>
<th>Category</th>
<th>Rule</th>
<th>Message</th>
<th>Line</th></tr>
<tr>
<tr>
<td> Error</td>
<td>imports</td>
<td>UnusedImports</td>
<td>Unused import - org.slf4j.Logger.</td>
<td>6</td></tr>
<tr>
<td>Error</td>
<td>imports</td>
<td>UnusedImports</td>
<td>Unused import - org.slf4j.LoggerFactory.</td>
<td>7</td></tr>
<tr>
<td>Error</td>
<td>imports</td>
<td>AvoidStarImport</td>
<td>Using the '.*' form of import should be avoided - org.springframework.web.bind.annotation.*.</td>
<td>11</td></tr>
<tr>
<td>Error</td>
<td>imports</td>
<td>UnusedImports</td>
<td>Unused import - java.io.PrintStream.</td>
<td>15</td></tr>
<td>Error</td>
<td>imports</td>
<td>UnusedImports</td>
<td>Unused import - java.util.Base64.</td>
<td>16</td></tr>
<td>Error</td>
<td>imports</td>
<td>UnusedImports</td>
<td>Unused import - java.util.List.</td>
<td>17</td></tr>
<tr>
<td>Error</td>
<td>sizes</td>
<td>LineLength</td>
<td>Line is longer than 80 characters (found 104).</td>
<td>36</td></tr>
<tr>
<td>Error</td>
<td>naming</td>
<td>LocalVariableName</td>
<td>Name 'Bytes' must match pattern '^[a-z][a-zA-Z0-9]*$'.</td>
<td>41</td></tr>
<tr>
<td>Error</td>
<td>sizes</td>
<td>LineLength</td>
<td>Line is longer than 80 characters (found 91).</td>
<td>43</td></tr>
</tbody>
</table>
<h2>Prodotto.java (dalla riga 1 alla 37)</h2>
<table>
<tbody>
<tr>
<th>Severity</th>
<th>Category</th>
<th>Rule</th>
<th>Message</th>
<th>Line</th></tr>
<tr>
<td>Error</td>
<td>imports</td>
<td>AvoidStarImport</td>
<td>Using the '.*' form of import should be avoided - jakarta.persistence.*.</td>
<td>3</td></tr>
<tr>
</tbody>
</table>

**Review by deg997 — COMMENTED** [review]
Ottimo, grande lavoro!

**Pull request merged**
